In [12]:
# modelling
from keras.models import save_model, load_model
from keras.preprocessing.image import ImageDataGenerator

import numpy as np

from sklearn.metrics import confusion_matrix

parent_dir = '../../'

In [2]:
model2 = load_model(parent_dir + 'models/model2', custom_objects = None, compile = True)

In [3]:
val_folder = parent_dir + 'data/seg_val/'
test_folder = parent_dir + 'data/seg_test/'
train_folder = parent_dir + 'data/seg_train/'

In [53]:
# test generator:
test_gen = ImageDataGenerator(rescale = 1. / 255).flow_from_directory(test_folder, batch_size = 300)

# train generator:
train_gen = ImageDataGenerator(rescale = 1. / 255).flow_from_directory(train_folder, batch_size = 1123)

# val generator:
val_gen = ImageDataGenerator(rescale = 1. / 255).flow_from_directory(val_folder, batch_size = 280)

Found 3000 images belonging to 6 classes.
Found 11237 images belonging to 6 classes.
Found 2804 images belonging to 6 classes.


In [54]:
# create the data sets
train_images, train_labels = next(train_gen)
test_images, test_labels = next(test_gen)
val_images, val_labels = next(val_gen)

In [16]:
train_img = train_images.reshape(train_images.shape[0], -1)
test_img = test_images.reshape(test_images.shape[0], -1)
val_img = val_images.reshape(val_images.shape[0], -1)


In [17]:
train_y = np.reshape(train_labels[:,0], (1123, 1))
test_y = np.reshape(test_labels[:,0], (300, 1))
val_y = np.reshape(val_labels[:,0], (280, 1))

Model 2 predictions on `test_img`

In [56]:
model2.predict(test_img)

array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]], dtype=float32)

In [57]:
preds = model2.predict(test_img)

In [49]:
y_hat = np.argmax(preds, axis = 0)

In [50]:
y_hat

array([  0, 111,   0, 111, 111,   0])

In [45]:
y_true = np.argmax(test_y, axis = 1)

In [46]:
y_true

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
test_y

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [9]:
train_gen.labels

array([0, 0, 0, ..., 5, 5, 5], dtype=int32)

In [11]:
train_gen.labels.shape

(11237,)

In [14]:
train_gen.image_shape

(299, 299, 3)

In [15]:
train_gen.classes

array([0, 0, 0, ..., 5, 5, 5], dtype=int32)

In [16]:
train_gen.classes.shape

(11237,)

In [17]:
train_gen.filenames

['buildings/0.jpg',
 'buildings/10006.jpg',
 'buildings/1001.jpg',
 'buildings/10014.jpg',
 'buildings/10029.jpg',
 'buildings/10032.jpg',
 'buildings/10056.jpg',
 'buildings/1009.jpg',
 'buildings/1012.jpg',
 'buildings/10126.jpg',
 'buildings/10161.jpg',
 'buildings/10176.jpg',
 'buildings/10185.jpg',
 'buildings/10196.jpg',
 'buildings/10198.jpg',
 'buildings/10205.jpg',
 'buildings/10210.jpg',
 'buildings/10231.jpg',
 'buildings/10251.jpg',
 'buildings/10252.jpg',
 'buildings/10257.jpg',
 'buildings/10266.jpg',
 'buildings/10278.jpg',
 'buildings/10295.jpg',
 'buildings/10303.jpg',
 'buildings/10306.jpg',
 'buildings/10310.jpg',
 'buildings/10312.jpg',
 'buildings/10316.jpg',
 'buildings/10318.jpg',
 'buildings/10328.jpg',
 'buildings/10350.jpg',
 'buildings/10357.jpg',
 'buildings/10362.jpg',
 'buildings/10367.jpg',
 'buildings/10374.jpg',
 'buildings/10402.jpg',
 'buildings/1041.jpg',
 'buildings/10421.jpg',
 'buildings/10444.jpg',
 'buildings/10452.jpg',
 'buildings/10466.jpg',


In [19]:
train_gen

In [21]:
train_gen.color_mode

'rgb'

In [22]:
train_gen.image_data_generator

In [23]:
train_gen.index_generator

<generator object Iterator._flow_index at 0x1a6576ddb0>

In [25]:
len(train_gen)

352

In [33]:
test_gen

In [29]:
model2.count_params

<bound method Layer.count_params of <keras.engine.sequential.Sequential object at 0x1a448f2cc0>>

I don't understand how to get predictions out of these models.  I don't know how to feed it the size it's looking for. 

In [32]:
model2.predict_classes(test_gen, batch_size = None)

ValueError: Error when checking input: expected dense_1_input to have 2 dimensions, but got array with shape (32, 299, 299, 3)

In [4]:
# train generator:
train_gen = ImageDataGenerator(rescale = 1. / 255).flow_from_directory(train_folder, target_size = (299, 299), batch_size = 32)

# val generator:
val_gen = ImageDataGenerator(rescale = 1. / 255).flow_from_directory(val_folder, target_size = (299, 299), batch_size = 32)

# test generator:
test_gen = ImageDataGenerator(rescale = 1. / 255).flow_from_directory(test_folder, target_size = (299, 299), batch_size = 32)

Found 11237 images belonging to 6 classes.
Found 2804 images belonging to 6 classes.
Found 3000 images belonging to 6 classes.


In [7]:
model2.predict_generator(test_gen, 3000//33)

ValueError: Error when checking input: expected dense_1_input to have 2 dimensions, but got array with shape (32, 299, 299, 3)

## Report Model 2:

In [19]:
report_model2 = load_model(parent_dir + 'models/report_model2', custom_objects = None, compile = True)

In [20]:
# train generator:
train_gen = ImageDataGenerator(rescale = 1. / 255).flow_from_directory(train_folder, target_size = (299, 299), batch_size = 32)

# val generator:
val_gen = ImageDataGenerator(rescale = 1. / 255).flow_from_directory(val_folder, target_size = (299, 299), batch_size = 32)

# test generator:
test_gen = ImageDataGenerator(rescale = 1. / 255).flow_from_directory(test_folder, target_size = (299, 299), batch_size = 32)

Found 11237 images belonging to 6 classes.
Found 2804 images belonging to 6 classes.
Found 3000 images belonging to 6 classes.


In [21]:
report_model2.predict_generator(test_gen)

array([[0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332],
       [0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332],
       [0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332],
       ...,
       [0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332],
       [0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332],
       [0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332]], dtype=float32)

In [26]:
preds = report_model2.predict_generator(test_gen)

In [27]:
preds_max = np.argmax(preds, axis = 1)

In [28]:
preds_max

array([3, 3, 3, ..., 3, 3, 3])

In [29]:
confusion_matrix(test_gen.labels, preds_max)

array([[  0,   0,   0, 437,   0,   0],
       [  0,   0,   0, 474,   0,   0],
       [  0,   0,   0, 553,   0,   0],
       [  0,   0,   0, 525,   0,   0],
       [  0,   0,   0, 510,   0,   0],
       [  0,   0,   0, 501,   0,   0]])

In [30]:
preds

array([[0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332],
       [0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332],
       [0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332],
       ...,
       [0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332],
       [0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332],
       [0.15720542, 0.16166498, 0.17134063, 0.17858744, 0.16130818,
        0.16989332]], dtype=float32)

In [33]:
test_gen.labels

array([0, 0, 0, ..., 5, 5, 5], dtype=int32)

In [34]:
set(test_gen.labels)

{0, 1, 2, 3, 4, 5}

In [24]:
test_gen.classes == test_gen.labels

array([ True,  True,  True, ...,  True,  True,  True])

In [25]:
test_gen.labels

array([0, 0, 0, ..., 5, 5, 5], dtype=int32)